# ---- Build stage ----
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o payments-service ./cmd/main.go

# ---- Final stage ----
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/payments-service .
COPY --from=builder /app/migrations ./migrations

EXPOSE 8080

CMD ["./payments-service"]